// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForAndroid',
    appId: '1:123456789012:android:dummyappid',
    messagingSenderId: '123456789012',
    projectId: 'vantage-419',
    storageBucket: 'vantage-419.appspot.com',
  );

  // TODO: Replace with your actual Firebase project configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForIos',
    appId: '1:123456789012:ios:dummyappid',
    messagingSenderId: '123456789012',
    projectId: 'vantage-419',
    storageBucket: 'vantage-419.appspot.com',
    iosBundleId: 'com.example.vantage419',
  );

  // TODO: Replace with your actual Firebase project configuration
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyApiKeyForMacos',
    appId: '1:123456789012:ios:dummyappid',
    messagingSenderId: '123456789012',
    projectId: 'vantage-419',
    storageBucket: 'vantage-419.appspot.com',
    iosBundleId: 'com.example.vantage419',
  );
}
